### ISSUE TITLE
[DEPRECATED]: community.network.panos_op has been removed

### ISSUE THREAD

**Issue by lboue** [PaloAltoNetworks/panos-ansible-upgrade-downgrade#9]
## [DEPRECATED]: community.network.panos_op has been removed

I am not able to use the manage_panos_software.yml playbook. It says "community.network.panos_op has been removed. Use modules from the paloaltonetworks.panos collection instead". 

## Current behavior

```
~/panos-ansible-upgrade-downgrade $ ansible-playbook -i inventory.yml ./manage_panos_software.yml -e 'desired_version=9.0.11' -e 'ip_address=10.10.10.131' -e 'username=admin' -e 'password=password'
[WARNING]: Found both group and host with same name: localhost
ERROR! [DEPRECATED]: community.network.panos_op has been removed. Use modules from the paloaltonetworks.panos collection instead. This feature was removed from community.network in version 2.0.0. Please update your playbooks.
```

## Steps to reproduce

1. git clone https://github.com/PaloAltoNetworks/panos-ansible-upgrade-downgrade.git     
2. cd panos-ansible-upgrade-downgrade
3. ansible-playbook -i inventory.yml ./manage_panos_software.yml -e 'desired_version=9.0.11' -e 'ip_address=10.10.10.131' -e 'username=admin' -e 'password=password'

## Context

I am trying to upgrade panos device with the manage_panos_software.yml playbook.

## Your Environment

- Version used: ansible 2.10.12
- Environment name: python version = 3.7.3
- Operating System and version : Raspbian GNU/Linux 10

```
ansible --version
ansible 2.10.12
  config file = None
  configured module search path = ['/home/pi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pi/.local/lib/python3.7/site-packages/ansible
  executable location = /home/pi/.local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

**Comment by nembery** [comment]
hi, this looks like you possibly don't have the paloaltonetworks.panos collection installed. 

You can install this via the following:

```
ansible-galaxy collection install paloaltonetworks.panos
```

See here for more information: https://galaxy.ansible.com/paloaltonetworks/panos

**Comment by lboue** [comment]
I had issues with the 'ansible-galaxy' command. 
`ImportError: cannot import name 'CollectionRequirement' from 'ansible.galaxy.collection' (/home/pi/.local/lib/python3.7/site-packages/ansible/galaxy/collect`

I works now with a fresh Ansible install.

Thanks
